version: "2"

services:
  cloudera:
    image: gethue/hue:latest
    hostname: hue
    container_name: spark_hue
    ports:
     - "8888:8888"
    #command: ./build/env/bin/hue runserver_plus 0.0.0.0:8888
    command: tail -f /dev/null
    volumes:
      - ./hue.ini:/hue/desktop/conf/hue.ini
    command: ./build/env/bin/hue runserver_plus 0.0.0.0:8888
